logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  session:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
    settings:
      trace: true
    path: /h2-console
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
        show_sql: true
        use_sql_comments: true
        format_sql: true