CREATE TABLE BRAND (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PRICE (
    ID INT NOT NULL AUTO_INCREMENT,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT NOT NULL,
    PRIORITY TINYINT,
    PRICE DECIMAL(10,2),
    CURR VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT FK_BRAND FOREIGN KEY (BRAND_ID)
        REFERENCES BRAND(ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(ID)
);