DROP TABLE IF EXISTS PRICE;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRICE_LIST;

CREATE TABLE BRAND (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
    ID INT NOT NULL AUTO_INCREMENT(35455,1),
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PRICE_LIST (
    ID INT NOT NULL AUTO_INCREMENT,
    FARE VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE PRICE (
    ID INT NOT NULL AUTO_INCREMENT,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT,
    PRICE DECIMAL(10,2),
    CURR VARCHAR(255),
    PRIMARY KEY (ID),
    CONSTRAINT FK_BRAND FOREIGN KEY (BRAND_ID)
        REFERENCES BRAND(ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(ID),
    CONSTRAINT FK_PRICE_LIST FOREIGN KEY (PRICE_LIST)
            REFERENCES PRICE_LIST(ID)
);