spring:
  datasource:
    url: jdbc:h2:file:/alicia.test.domain/src/main/resources/demo.sql
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect